version: "3"

services:
  reverseproxy:
    build: ./reverseproxy
    ports:
      - 8080:8080
    restart: always
  app:
    build:
      context: .
    # run the wait_for_db command and after it succeeds runserver
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --no-input --clear &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    env_file: .env
    depends_on:
      - db
      - reverseproxy
  db:
    image: postgres:10-alpine
    env_file: .env.db
    volumes:
      - my-datavolume:/var/lib/postgresql/data
  nginx1:
    build: ./nginx
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    restart: always
    depends_on:
      - reverseproxy
      - app
  nginx2:
    build: ./nginx
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    restart: always
    depends_on:
      - reverseproxy
      - app
  nginx3:
    build: ./nginx
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    restart: always
    depends_on:
      - reverseproxy
      - app
  nginx4:
    build: ./nginx
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    restart: always
    depends_on:
      - reverseproxy
      - app
  nginx5:
    build: ./nginx
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    restart: always
    depends_on:
      - reverseproxy
      - app


volumes:
  my-datavolume:
  static_volume:
  media_volume:
