version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # run the wait_for_db command and after it succeeds runserver
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      # TODO change this with an encrypted password for production
      - DB_PASS=supersecretpassword
    depends_on:
      - db

      
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRESS_DB=postgres
      - POSTGRES_USER=postgres
      # TODO change this with an encrypted password for production
      - POSTGRES_PASSWORD=supersecretpassword